import { motion } from "motion/react";
import { type Language } from "../lib/i18n";

interface WinnerShowcaseProps {
  lang: Language;
}

export function WinnerShowcase({ lang }: WinnerShowcaseProps) {
  return (
    <section className="relative py-12 px-4 sm:px-6 lg:px-8 overflow-hidden bg-background">
      {/* Background patterns */}
      <div className="absolute inset-0 z-0 opacity-[0.03] pointer-events-none">
        <svg className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
              <path d="M 40 0 L 0 0 0 40" fill="none" stroke="currentColor" strokeWidth="1" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#grid)" />
        </svg>
      </div>

      <div className="max-w-7xl mx-auto relative z-10">
        <div className="text-center mb-12">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="inline-block px-4 py-1.5 mb-6 rounded-full bg-primary/10 text-primary text-sm font-semibold tracking-wide uppercase"
          >
            {lang === 'ar' ? 'الفائز بمسابقة جيمناي' : 'Gemini Competition Winner'}
          </motion.div>
          
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-4xl md:text-5xl lg:text-6xl font-black mb-6 tracking-tight"
          >
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-[#4285f4] via-[#ea4335] to-[#f9ab00]">
              {lang === 'ar' ? 'أفضل صورة من إنشاء Gemini' : 'Best Photo Generated by Gemini'}
            </span>
          </motion.h2>
          
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-lg text-muted-foreground max-w-2xl mx-auto"
          >
            {lang === 'ar' 
              ? 'نهنئ الفائز في مسابقة GDG Mustaqbal University لأفضل صورة إبداعية باستخدام تقنيات الذكاء الاصطناعي من جوجل.'
              : 'Congratulations to the winner of the GDG Mustaqbal University competition for the most creative photo using Google\'s Gemini AI technologies.'}
          </motion.p>
        </div>

        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="relative group mt-8 max-w-2xl mx-auto"
        >
          {/* Decorative glow */}
          <div className="absolute -inset-1.5 bg-gradient-to-r from-[#4285f4] via-[#ea4335] to-[#f9ab00] rounded-[2.5rem] opacity-25 blur-2xl group-hover:opacity-50 transition duration-1000 group-hover:duration-200"></div>
          
          {/* Main Image Container */}
          <div className="relative aspect-[16/8] rounded-[2rem] overflow-hidden border border-border bg-card shadow-2xl">
            <img 
              src="/IMG_7951.jpg" 
              alt="Winner: Best Photo Generated by Gemini" 
              className="w-full h-full object-cover transition duration-700 group-hover:scale-105"
            />
            
            {/* Overlay */}
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 flex items-end p-8 md:p-12">
              <div className="text-white">
                <p className="text-sm font-medium uppercase tracking-[0.2em] mb-2 opacity-80">
                  {lang === 'ar' ? 'الحدث' : 'Event'}
                </p>
                <h3 className="text-2xl md:text-3xl font-bold">
                  {lang === 'ar' ? 'مسابقة GDG للإبداع' : 'GDG Creativity Competition'}
                </h3>
              </div>
            </div>
          </div>
          
          {/* Bottom badge */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.4 }}
            className="absolute -bottom-6 left-1/2 -translate-x-1/2 bg-background border border-border shadow-xl rounded-2xl px-8 py-4 flex items-center gap-4 whitespace-nowrap"
          >
            <div className="w-10 h-10 rounded-full bg-[#f9ab00] flex items-center justify-center text-white">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6"/><path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18"/><path d="M4 22h16"/><path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22"/><path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22"/><path d="M18 2H6v7a6 6 0 0 0 12 0V2Z"/></svg>
            </div>
            <div>
              <p className="text-xs text-muted-foreground uppercase font-bold tracking-wider">
                {lang === 'ar' ? 'المركز الأول' : '1st Place Winner'}
              </p>
              <p className="font-bold">Nora Raad</p>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
}
